import { afterAll, beforeAll, expect, test } from "bun:test";
import { chromium, type Browser } from "playwright";
import { rmSync } from "node:fs";
import { compileCanvas } from "../src/compile";
import { typecheckCanvas } from "../src/typecheck";
import { tempDir, writeCanvas } from "../src/test/fixtures";
import { ROUTING_CANVAS } from "../src/test/routing";
let browser: Browser;
let server: ReturnType<typeof Bun.serve>;
let dir: string;
beforeAll(async () => {
  dir = tempDir("canvas-routing-");
  const source = writeCanvas(dir, "routes", ROUTING_CANVAS);
  expect(typecheckCanvas(source)).toEqual([]);
  const compiled = await compileCanvas(source);
  expect(compiled.ok).toBe(true);
  const host = await Bun.build({ entrypoints: [new URL("../src/runtime/navigation-host.ts", import.meta.url).pathname], target: "browser", format: "iife" });
  expect(host.success).toBe(true);
  const hostJs = await host.outputs[0]!.text();
  server = Bun.serve({ hostname: "127.0.0.1", port: 0, fetch(request) {
    const url = new URL(request.url);
    const external = url.pathname.startsWith("/sales");
    const context = external ? { route: { path: (url.pathname.slice(6) || "/") + url.search, basePath: "/sales", external: true } } : {};
    const frame = `<div id="root"></div><script>window.__herdrCanvas=${JSON.stringify(context)};<\/script><script type="module">${compiled.js!.replace(/<\/script/gi, "<\\/script")}<\/script>`;
    return new Response(`<iframe sandbox="allow-scripts"></iframe><script>const frame=document.querySelector('iframe');frame.srcdoc=${JSON.stringify(frame).replaceAll("<", "\\u003c")};window.__canvasNavigationHost={frame,basePath:'/sales'};${hostJs.replace(/<\/script/gi, "<\\/script")}<\/script>`, { headers: { "content-type": "text/html" } });
  } });
  browser = await chromium.launch({ headless: true });
}, 60000);
afterAll(async () => { await browser?.close(); server?.stop(true); if (dir) rmSync(dir, {recursive:true,force:true}); });

test("embedded routing supports layouts, params, queries and history without navigating the viewer", async () => {
  const page = await browser.newPage();
  page.setDefaultTimeout(5000);
  page.on("pageerror", error => console.error(error.message));
  const url = `http://127.0.0.1:${server.port}/embed`;
  await page.goto(url);
  const frame = page.frameLocator("iframe");
  await frame.getByRole("heading", {name:"Home page"}).waitFor();
  await frame.getByRole("link", {name:"Account",exact:true}).click();
  await frame.getByRole("heading", {name:"Account 123"}).waitFor();
  await frame.getByText("Account layout", {exact:true}).waitFor();
  await frame.getByText("Tab: activity", {exact:true}).waitFor();
  await frame.getByText("Hash: #latest", {exact:true}).waitFor();
  expect(page.url()).toBe(url);
  await frame.getByRole("button", {name:"Back",exact:true}).click();
  await frame.getByRole("heading", {name:"Home page"}).waitFor();
  expect(await frame.getByRole("link", {name:"External"}).getAttribute("href")).toBe("https://example.com");
  await page.close();
});

test("standalone deep links, relative links, reload, replace and browser back/forward share one history", async () => {
  const page = await browser.newPage();
  page.setDefaultTimeout(5000);
  page.on("pageerror", error => console.error(error.message));
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  const origin = `http://127.0.0.1:${server.port}`;
  await page.goto(`${origin}/sales/accounts/123?tab=activity#latest`);
  const frame = page.frameLocator("iframe");
  await frame.getByRole("heading", {name:"Account 123"}).waitFor();
  await frame.getByText("Hash: #latest", {exact:true}).waitFor();
  expect(await frame.getByRole("link", {name:"Next account"}).getAttribute("href")).toBe("/sales/accounts/456");
  await frame.getByRole("link", {name:"Next account"}).click();
  await frame.getByRole("heading", {name:"Account 456"}).waitFor();
  expect(page.url()).toBe(`${origin}/sales/accounts/456`);
  await page.reload();
  await frame.getByRole("heading", {name:"Account 456"}).waitFor();
  await page.goBack();
  await frame.getByRole("heading", {name:"Account 123"}).waitFor();
  await page.goForward();
  await frame.getByRole("heading", {name:"Account 456"}).waitFor();
  await frame.getByRole("button", {name:"Replace",exact:true}).click();
  await frame.getByRole("heading", {name:"Account 789"}).waitFor();
  await frame.getByText('State: {"from":"replace"}', {exact:true}).waitFor();
  await frame.getByRole("button", {name:"Back",exact:true}).click();
  await frame.getByRole("heading", {name:"Account 123"}).waitFor();
  expect(page.url()).toBe(`${origin}/sales/accounts/123?tab=activity#latest`);
  expect(errors).toEqual([]);
  await page.close();
}, 60000);
